server {
    listen 443 ssl;
    server_name 35.239.192.226.sslip.io;
    ssl_certificate /etc/letsencrypt/live/35.239.192.226.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/35.239.192.226.sslip.io/privkey.pem;
    location = /.well-known/appspecific/com.tesla.3p.public-key.pem {
        alias /opt/tesla-fleet-telemetry/com.tesla.3p.public-key.pem;
        default_type application/x-pem-file;
        add_header Cache-Control "no-store";
    }
    location / {
        return 404;
    }
}
